version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - BASE_URL=http://localhost:8080

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: