name: Docker for Log Analytics

on:
  push:
    paths:
    - 'log_analytics/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -f Dockerfile -t log-analytics .
      working-directory: log_analytics

    - name: Run Docker image
      run: docker run --rm log-analytics
      working-directory: log_analytics