name: Docker Compose Test

on:
  push:
    paths:
    - 'system_design/**'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d
      working-directory: system_design

    - name: Run curl commands
      run: |
        sleep 10 # wait for services to start
        response=$(curl -s -X POST http://127.0.0.1:8080/newurl -H "Content-Type: application/json" -d '{"url": "https://www.youtube.com"}')
        shortenUri=$(echo $response | jq -r '.shortenUri')
        curl $shortenUri -v -I
